# Display name of workflow
name: Chaining Jobs

# Controls when the action will run. workflow runs when manually triggered using the UI or API.
on:
 workflow_dispatch:
   # Inputs the workflow accepts.
   inputs:
     run-job-3:  # name of the input
       description: "Run Job 3"
       required: true
       type: boolean  # it will be a checkbox
jobs:
 job-1:  # Name of the job
  name: Job 1    # display name of the job
  runs-on: ubuntu-latest
  steps:
    - name: Output for Job 1
    run: echo "Hello from Job 1. Job 3 wants to run? ${{github.event.inputs.run-job-3}}"

job-2: # name of the job
 name: Job 2 # display name of the job
 runs-on: ubuntu-latest  # this job and above job will be running of 2 different runners
 needs: # this need keyword allow us to control order of the job going to run, so here it means Job 2 will run once the job 1 get completed/finishes
   - job-1
steps:
 - name: Output for job 2
   run: echo "Hello from Job 2"
job-3:
  name: job 3
  if: github.event.inputs.run-job-3 == 'true'
  runs-on: ubuntu-latest
  needs: # this job will run once the job 1 finished running. and this will run if user want to run job three and user answer is checked through above checkbox
   - job-1
   steps:
   - name: Output for Job 3
     run: echo "Hello from Job 3"
  job-4
   name: Job 4
   runs-on: ubuntu-latest
   # if: always()
   needs: # this job 4 will run once job 2 and job 3 will finish running or completed successfully
    - job-2
    - job-3
  steps:
   - name: Output for Job 4
     run: echo "Hello from Job 4"
   
 


