# This is a basic workflow to help you get started with Actions

name: Variables and Context

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
  #  branches: [ "main" ]
 # pull_request:
 #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
       

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Display name of the step
      - name: Dump GitHub context
        # Creating environment varialbe just for this step or only avaiable for this step we can say
        env:   
         Mera_Variable_GITHUB_CONTEXT: ${{ toJSON(github)}}   # here Mera_Variable_GITHUB_CONTEXT is a variable that save the github context value after converting into json
        run: echo "$Mera_Variable_GITHUB_CONTEXT"  # echo the value of the variable

     
